pub mod manual;
pub mod omp;
pub mod opencode;

use anyhow::{anyhow, Result};
use serde_json::Value;
use std::path::Path;

/// The single source of truth for which executor adapters `ctl` supports.
/// Every surface — CLI dispatch, capability queries, run/ingest lifecycle, and
/// the conformance suite — derives from this list plus [`adapter_for`]. Adding
/// an adapter is a one-line change here and one `adapter_for` arm; the
/// conformance suite then iterates this list and forces the newcomer to satisfy
/// the contract, so a half-wired adapter fails tests instead of shipping.
///
/// Names are matched **exactly**: no case-folding, trimming, or aliases. This
/// keeps the audit trail (`adapter` / evidence `source`) unambiguous.
pub const SUPPORTED_ADAPTERS: &[&str] = &["omp", "opencode"];

/// The supported adapter names (see [`SUPPORTED_ADAPTERS`]).
pub fn supported_adapters() -> &'static [&'static str] {
    SUPPORTED_ADAPTERS
}

/// Resolve an adapter name to its [`ExecutorAdapter`] implementation. The only
/// resolver in the codebase — every run-lifecycle site routes through it, so the
/// supported set lives in exactly one place.
pub fn adapter_for(name: &str) -> Result<Box<dyn ExecutorAdapter>> {
    match name {
        "omp" => Ok(Box::new(omp::OmpAdapter)),
        "opencode" => Ok(Box::new(opencode::OpenCodeAdapter)),
        other => Err(anyhow!("Unknown adapter: {}", other)),
    }
}

/// Run manifest generated by prepare_run, consumed by the executor.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RunManifest {
    pub schema: String,
    pub run_id: String,
    pub task_id: String,
    pub adapter: String,
    pub assignment_path: String,
    pub worktree_path: String,
    pub lease_id: String,
    pub write_allow: Vec<String>,
    pub write_deny: Vec<String>,
    pub gates: Vec<String>,
    pub created_at: String,
}

/// Executor adapter trait — defines the contract for all execution adapters.
/// Defined in adapters/ layer (not domain/) per MODULE-004.
pub trait ExecutorAdapter {
    /// Adapter identifier (e.g., "manual", "omp").
    fn adapter_name(&self) -> &str;

    /// Report adapter capabilities as a JSON value.
    fn capabilities(&self) -> Value;

    /// Prepare a run manifest for the given task and worktree.
    #[allow(clippy::too_many_arguments)]
    fn prepare_run(
        &self,
        task_id: &str,
        run_id: &str,
        lease_id: &str,
        worktree: &Path,
        write_allow: &[String],
        write_deny: &[String],
        gates: &[String],
    ) -> Result<RunManifest>;

    /// Validate an agent output file against the adapter's expected format.
    fn validate_output(&self, output: &Value) -> Result<()>;
}

#[cfg(test)]
mod conformance {
    //! The shared adapter conformance suite. Every supported adapter is run
    //! through the *same* assertions — there are deliberately no per-adapter
    //! "looks similar" test copies. "Supported" means "passes this contract".
    use super::*;

    /// The minimal contract every [`ExecutorAdapter`] must satisfy to be a
    /// supported adapter. Object-safe by `&dyn`, so the same assertions run over
    /// every entry in the registry.
    fn assert_adapter_conformance(name: &str, adapter: &dyn ExecutorAdapter) {
        // (3) capabilities are queryable and self-describe the same name.
        assert_eq!(
            adapter.adapter_name(),
            name,
            "adapter_name() must equal its registry name"
        );
        let caps = adapter.capabilities();
        assert_eq!(
            caps["adapter"], name,
            "{name}: capabilities.adapter must match the adapter name"
        );
        assert!(
            caps["output_format"].is_string(),
            "{name}: capabilities must declare an output_format"
        );
        assert!(
            caps["capabilities"].is_array(),
            "{name}: capabilities.capabilities must be an array"
        );

        // (4) prepare_run stamps the manifest with the correct adapter name and
        //     threads identifiers through unchanged.
        let manifest = adapter
            .prepare_run(
                "task-x",
                "run-x",
                "lease-x",
                Path::new("/tmp/wt"),
                &["src".to_string()],
                &[],
                &["cargo_check".to_string()],
            )
            .expect("prepare_run must succeed for a well-formed request");
        assert_eq!(
            manifest.adapter, name,
            "{name}: manifest.adapter must match the adapter name"
        );
        assert_eq!(manifest.task_id, "task-x");
        assert_eq!(manifest.run_id, "run-x");
        assert_eq!(manifest.lease_id, "lease-x");
        assert!(
            !manifest.schema.is_empty(),
            "{name}: manifest must declare a schema"
        );

        // (5) Correct source + touched_files passes.
        let good = serde_json::json!({ "source": name, "touched_files": [] });
        assert!(
            adapter.validate_output(&good).is_ok(),
            "{name}: output with matching source must validate"
        );

        // (6) Missing touched_files is rejected.
        let missing_tf = serde_json::json!({ "source": name });
        assert!(
            adapter.validate_output(&missing_tf).is_err(),
            "{name}: output missing touched_files must be rejected"
        );

        // (7) Wrong source is rejected — including every *other* supported
        //     adapter's name (e.g. an opencode manifest claiming source="omp").
        for other in supported_adapters() {
            if *other == name {
                continue;
            }
            let cross = serde_json::json!({ "source": other, "touched_files": [] });
            assert!(
                adapter.validate_output(&cross).is_err(),
                "{name} adapter must reject foreign source={other}"
            );
        }
        let empty_source = serde_json::json!({ "touched_files": [] });
        assert!(
            adapter.validate_output(&empty_source).is_err(),
            "{name}: output with empty/absent source must be rejected"
        );
    }

    /// (1) + (10) Tripwire: every registered adapter resolves and conforms.
    /// Adding an adapter to `SUPPORTED_ADAPTERS` automatically subjects it to
    /// the full contract here; a half-wired adapter fails this test.
    #[test]
    fn every_supported_adapter_resolves_and_conforms() {
        assert!(
            !supported_adapters().is_empty(),
            "the supported-adapter registry must not be empty"
        );
        for name in supported_adapters() {
            let adapter = adapter_for(name)
                .unwrap_or_else(|e| panic!("supported adapter '{name}' must resolve: {e}"));
            assert_adapter_conformance(name, adapter.as_ref());
        }
    }

    /// (2) + (9) Unknown names are rejected, and matching is exact: no
    /// case-folding, trimming, or aliasing.
    #[test]
    fn unknown_adapter_is_rejected_and_matching_is_exact() {
        // `Box<dyn ExecutorAdapter>` isn't Debug, so match rather than unwrap_err.
        let err = match adapter_for("definitely-not-an-adapter") {
            Ok(_) => panic!("an unknown adapter must not resolve"),
            Err(e) => e.to_string(),
        };
        assert!(err.contains("Unknown adapter"), "got: {err}");
        assert!(adapter_for("").is_err(), "empty name must be rejected");
        assert!(
            adapter_for("OMP").is_err(),
            "names are case-sensitive: 'OMP' != 'omp'"
        );
        assert!(
            adapter_for(" omp").is_err(),
            "names are not trimmed: ' omp' != 'omp'"
        );
    }

    /// Tripwire for the documented set: if you add or remove an adapter, update
    /// this list — and confirm it passes `assert_adapter_conformance` above.
    #[test]
    fn registry_lists_exactly_the_known_adapters() {
        assert_eq!(
            supported_adapters(),
            &["omp", "opencode"],
            "supported-adapter registry changed — update the conformance suite + CLI docs"
        );
    }
}
