pub mod manual;
pub mod omp;

use anyhow::Result;
use serde_json::Value;
use std::path::Path;

/// Run manifest generated by prepare_run, consumed by the executor.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RunManifest {
    pub schema: String,
    pub run_id: String,
    pub task_id: String,
    pub adapter: String,
    pub assignment_path: String,
    pub worktree_path: String,
    pub lease_id: String,
    pub write_allow: Vec<String>,
    pub write_deny: Vec<String>,
    pub gates: Vec<String>,
    pub created_at: String,
}

/// Executor adapter trait — defines the contract for all execution adapters.
/// Defined in adapters/ layer (not domain/) per MODULE-004.
pub trait ExecutorAdapter {
    /// Adapter identifier (e.g., "manual", "omp").
    fn adapter_name(&self) -> &str;

    /// Report adapter capabilities as a JSON value.
    fn capabilities(&self) -> Value;

    /// Prepare a run manifest for the given task and worktree.
    #[allow(clippy::too_many_arguments)]
    fn prepare_run(
        &self,
        task_id: &str,
        run_id: &str,
        lease_id: &str,
        worktree: &Path,
        write_allow: &[String],
        write_deny: &[String],
        gates: &[String],
    ) -> Result<RunManifest>;

    /// Validate an agent output file against the adapter's expected format.
    fn validate_output(&self, output: &Value) -> Result<()>;
}
